### ISSUE TITLE
Socket location shouldn't use os.tmpdir()

### ISSUE THREAD

**Issue by ToadKing** [mnichols/monogamous#1]
On Mac OS X, your TMPDIR can be different if you launch your application from a .pkg installer. This location is deleted by the time the program can be launched and boot fails.

**Comment by mnichols** [comment]
@ToadKing if you are using this on electron you probably want this : https://github.com/atom/electron/blob/v0.34.1/docs/api/app.md#appmakesingleinstancecallback

Closing for now. Reopen with PR if needed
